channels:
  - conda-forge
  - bioconda
dependencies:
  - r-optparse=1.7.5
  - r-readr
  - r-r.utils
  - r-data.table=1.17.0
  - bioconductor-summarizedexperiment=1.36.0
  - bioconductor-rtracklayer
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-rsamtools
  - bioconductor-singlecellexperiment=1.28.0
  - bioconductor-zellkonverter=1.16.0
  - bioconductor-scrnaseq=2.20.0
  - bioconductor-rhdf5
  - bioconductor-hdf5array
  - r-coloc=5.2.3
  - r-susier=0.12.35
  - r-bigsnpr
  - r-stringi
  - r-stringr
  - r-reshape2
  - r-igraph
  - r-purrr
  - r-tidyr
  - r-dplyr
  - r-plyr
  - r-matrix=1.7_3
  - r-corrplot
  - r-patchwork
  - r-ggplot2
  - r-cowplot
  - r-rfast
  - r-anndata=0.7.5.6
  - tabix=1.11
  - bioconductor-rhtslib
  - pandas=2.2.3
  - numpy=2.2.6
  - anndata=0.11.4
  - plink2=2.00a5.10
  - gcta=1.94.1
