channels:
  - conda-forge
  - bioconda
dependencies:
  - r-optparse=1.7.4
  - r-readr=2.1.5
  - r-r.utils=2.12.3
  - r-data.table=1.15.2
  - bioconductor-rtracklayer=1.62.0
  - bioconductor-genomicranges=1.54.1
  - bioconductor-iranges=2.36.0
  - bioconductor-rsamtools=2.18.0
