site_name: Flanders-nf-pipeline
site_author: Arianna Landini
repo_name: "GitHub"
repo_url: "https://github.com/Biostatistics-Unit-HT/Flanders.git"
edit_uri: ""
copyright: "This pipeline is licensed under the MIT license"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  font:
    code: Roboto Mono
    text: Roboto
  palette:
    primary: blue
    accent: blue

nav:
  - Home: index.md
  - Quick start: quick-start.md

markdown_extensions:
  - toc:
      toc_depth: 3
